name: CI

on: push

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        zsh-version: ['5.9']

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        if [[ "${{ runner.os }}" == "macOS" ]]; then
          brew install zsh fzf
        else
          sudo apt-get update
          sudo apt-get install -y zsh fzf
        fi
    - name: Run tests
      run: |
        ./tests/run_tests.zsh
